# Generated by Django 5.0.2 on 2024-02-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='PoI internal ID')),
                ('name', models.CharField(max_length=72, verbose_name='PoI name')),
                ('external_id', models.CharField(max_length=64, verbose_name='PoI external ID')),
                ('category', models.CharField(max_length=32, verbose_name='PoI category')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Avg. rating')),
                ('description', models.TextField(blank=True, null=True, verbose_name='PoI description')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='PoI latitude')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='PoI longitude')),
            ],
        ),
    ]
