# Generated by Django 5.0.2 on 2024-02-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='name',
            field=models.CharField(max_length=256, verbose_name='PoI name'),
        ),
    ]
